---

- name: 'upload and run go.sh'
  script: '{{ role_path }}/files/go.sh'

- name: 'upload config.json'
  copy: 
    src: '{{ v2ray_config_file_path }}'
    dest: '/etc/v2ray/config.json'
    owner: root
    group: root
    mode: 0600
  notify:
  - restart v2ray